// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE-eOVyVJ5ycrhTWF-FKh2m32P8NCFUPA',
    appId: '1:654498817903:web:e0ae2f301bb712f194aa9a',
    messagingSenderId: '654498817903',
    projectId: 'agroresearch-pro',
    authDomain: 'agroresearch-pro.firebaseapp.com',
    storageBucket: 'agroresearch-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MV2YHnGy3B-p9Uqe0AA7-aTM5Lm-iYk',
    appId: '1:654498817903:android:f9997af0548fe66e94aa9a',
    messagingSenderId: '654498817903',
    projectId: 'agroresearch-pro',
    storageBucket: 'agroresearch-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAebynBYDq-7qErIP3dqWCUlqVF3RfWjuo',
    appId: '1:654498817903:ios:9fa4653175c1bf7a94aa9a',
    messagingSenderId: '654498817903',
    projectId: 'agroresearch-pro',
    storageBucket: 'agroresearch-pro.firebasestorage.app',
    iosBundleId: 'com.example.agroResearchPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE-eOVyVJ5ycrhTWF-FKh2m32P8NCFUPA',
    appId: '1:654498817903:web:4413258cc5207ed594aa9a',
    messagingSenderId: '654498817903',
    projectId: 'agroresearch-pro',
    authDomain: 'agroresearch-pro.firebaseapp.com',
    storageBucket: 'agroresearch-pro.firebasestorage.app',
  );
}
